# Generated by Django 5.1 on 2024-08-25 09:50

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to=jobs.models.upload_resume),
        ),
    ]
